name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CI: true
  HUSKY: 0

jobs:
  test:
    name: Node v${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        node-version: [14, 16, 18]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Update npm
        shell: bash
        run: npm install -g npm@8
      - name: Install dependencies
        shell: bash
        run: npm ci
      - name: Run tests
        shell: bash
        run: npm run test:cov
      - name: Upload coverage to CodeCov
        shell: bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_BRANCH: ${{ github.head_ref || github.ref }}
        run: npx codecov --disable=gcov --build=${{ matrix.os }}@${{ matrix.node-version }} --branch=${GITHUB_BRANCH#refs/heads/}
