name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Node v${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [8.x, 10.x, 12.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install and test
      shell: bash
      run: |
        npm install --global npm@6.11.x
        npm ci
        npm run test:coverage
      env:
        CI: true
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v1
      with:
        name: coverage
        path: coverage/
