name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CI: true

jobs:
  test:
    name: Node v${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        node-version: [12, 14, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        shell: bash
        run: npm ci
      - name: Run tests
        shell: bash
        run: npm run test:cov
      - name: Upload coverage to CodeCov
        shell: bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_BRANCH: ${{ github.head_ref || github.ref }}
        run: npx codecov --disable=gcov --build=${{ matrix.os }}@${{ matrix.node-version }} --branch=${GITHUB_BRANCH#refs/heads/}
